---
buildMetadata:
  - managedByLabel
  - originAnnotations
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: ca-issuer-cred
    namespace: cert-manager
    type: kubernetes.io/tls
    files:
      - tls.crt=../../config/pki/intermediate.pem
      - tls.key=../../config/pki/intermediate-key.pem
  - name: cloudflare-api-token
    namespace: kube-system
    envs:
      - .env
