---
buildMetadata:
  - managedByLabel
  - originAnnotations
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: ca-issuer-cred
    namespace: kcm-system
    type: kubernetes.io/tls
    files:
      - tls.crt=../../../config/pki/intermediate.pem
      - tls.key=../../../config/pki/intermediate-key.pem
  # - name: cloudflare-api-token
  #   namespace: kube-system
  #   envs:
  #     - cf.env
  - name: kcm-cred
    namespace: kcm-system
    envs:
      - kcm.env
