---
namespace: kcm-system
buildMetadata:
  - managedByLabel
  - originAnnotations
commonLabels:
  k0rdent.mirantis.com/managed: "true"
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ca.yaml
  - edns.yaml
  - gateway.yaml
  - knative.yaml
  - monitoring.yaml
  - openstack.yaml
  - pinniped.yaml
  # - crd.yaml
