---
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: devbox
spec:
  hosts:
    - role: controller+worker
      noTaints: true
      ssh:
        address: 192.168.0.105
        keyPath: ~/.ssh/id_ed25519
        port: 22
        user: admin
      installFlags:
        - --kubelet-extra-args=--cgroup-driver=systemd
      files:
        # - # custom resources definitions
        #   name: crds
        #   src: ./crds
        #   dstDir: /var/lib/k0s/manifests/crds
        - # secrets
          name: secrets
          src: ./manifests/secret.yaml
          dst: /var/lib/k0s/manifests/resources/secrets.yaml
  k0s:
    version: v1.33.1+k0s.1
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: devbox
      spec:
        api:
          sans:
            - devbox.dev.local
        network:
          provider: custom
        featureGates:
          - name: UserNamespacesSupport
            enabled: true
        extensions:
          helm:
            charts:
              - # cilium cni
                name: cni
                chartname: oci://ghcr.io/labsonline/charts/cni
                namespace: kube-system
                order: 1
                version: 1.0.3
                values: |
                  cilium:
                    operator:
                      replicas: 1
                    peer:
                      authSecretRef: bgp-cred
                      gracefulRestart: true
                      holdTimeSec: 9
                      keepAliveTimeSec: 3
                      multiHop: 4
                      restartTimeSec: 15
                      addressFamilies:
                        - afi: ipv4
                          safi: unicast
                          advertisements:
                            matchLabels:
                              advertise: bgp
                    instances:
                      - name: cilium
                        localASN: 65000
                        overrides:
                          enabled: true
                        peers:
                          - name: peer-1
                            peerASN: 65000
                            peerAddress: fd00:10:0:0::1
                            peerConfigRef:
                              name: cni-resources-peer-config
                    pool:
                      enabled: true
                      cidr: 172.16.22.0/24
              - # TODO: ceph csi
                name: csi
                chartname: oci://ghcr.io/labsonline/charts/csi
                namespace: kube-system
                order: 3
                version: 1.0.2
                values: ""
              - # TODO: ceph csi resources
                name: csi-resource
                chartname: oci://ghcr.io/labsonline/charts/csi
                namespace: kube-system
                order: 4
                version: 1.0.2
                values: ""
              - # edns
                name: edns
                chartname: oci://ghcr.io/labsonline/charts/edns
                namespace: kube-system
                order: 5
                version: 1.19.0
                values: |
                  endpoints:
                    - name: a-devbox-dev-local
                      records:
                        - name: devbox.dev.local
                          targets:
                            - 192.168.0.105
                  external-dns:
                    enabled: true
                    env:
                    - name: EXTERNAL_DNS_RFC2136_TSIG_KEYNAME
                      valueFrom:
                        secretKeyRef:
                          key: name
                          name: externaldns-tsig-secret
                    - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
                      valueFrom:
                        secretKeyRef:
                          key: secret
                          name: externaldns-tsig-secret
                    extraArgs:
                    - --rfc2136-host=192.168.0.105
                    - --rfc2136-port=53
                    - --rfc2136-tsig-secret-alg=hmac-sha256
                    - --rfc2136-zone=dev.local
                    - --rfc2136-tsig-axfr
                    provider:
                      name: rfc2136
              - # gateway
                name: gw
                chartname: oci://ghcr.io/labsonline/charts/gateway
                namespace: kube-system
                order: 5
                version: 1.0.3
                values: |
                  routes: []
                  gateways:
                    - name: default-gateway
                      className: cilium
                      listeners:
                        - name: http
                          port: 80
                          protocol: HTTP
                          allowedRoutes:
                            namespaces:
                              from: All
                        - name: https
                          port: 443
                          protocol: HTTPS
                          hostname: "*.dev.local"
                          allowedRoutes:
                            namespaces:
                              from: All
                          tls:
                            mode: Terminate
                            certificateRefs:
                              - name: default-gw-cert
                                issuer: ca-issuer
                    - name: tls-gateway
                      className: cilium
                      listeners:
                        - name: tls
                          port: 443
                          protocol: TLS
                          allowedRoutes:
                            namespaces:
                              from: All
                            kinds:
                              - kind: TLSRoute
                          tls:
                            mode: Passthrough
              - # TODO: openstack deployment
                name: osdpl
                chartname: oci://ghcr.io/labsonline/charts/openstack
                namespace: osh-system
                order: 6
                version: 1.0.3
                values: ""
              - # TODO: kubernetes cluster manager
              - # certificate authority
                name: ca
                chartname: oci://ghcr.io/labsonline/charts/ca
                namespace: kcm-system
                order: 8
                version: 1.0.4
                values: |
                  issuers:
                    - name: self-signed-ca-issuer
                      clustered: true
                      selfSigned: true
                      secret:
                        create: false
        telemetry:
          enabled: false
