---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: adopted
networking:
  # disableDefaultCNI: true
  apiServerAddress: 0.0.0.0
  apiServerPort: 6443
featureGates:
  UserNamespacesSupport: true
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
        listenAddress: 0.0.0.0
      - containerPort: 443
        hostPort: 443
        protocol: TCP
        listenAddress: 0.0.0.0
