---
apiVersion: v1
kind: Secret
metadata:
  name: externaldns-tsig-secret
  namespace: kube-system
stringData:
  name: externaldns
  secret: "${EXTERNAL_DNS_SECRET}"
---
apiVersion: v1
kind: Secret
metadata:
  name: externaldns-tsig-secret
  namespace: kcm-system
stringData:
  secret: "${EXTERNAL_DNS_SECRET}"
